### ISSUE TITLE
This effort is doomed. You're trying to build a full encyclopedia of all modern technology without realizing it.

### ISSUE THREAD

**Issue by marcusmueller** [civboot/civboot#1]
I was [encouraged to comment here](https://electronics.stackexchange.com/questions/528893/which-semiconductors-are-good-candidates-for-constructing-a-cpu/528894?noredirect=1#comment1362965_528894), but I don't want to foster a discussion, sorry.

* The premise of this is a fallacy: it's not a *problem* that nobody in our society knows how everything works. Or, really, how everything in every halfway complex device works. It's a boon of the fact that the last millennia of human civilization have led to so many disciplines that we can combine their output to build modern devices. There's no demand for what Civboot offers: it's already there. You "just" have to go and read the basics of each discipline.
* The whole deal is "too rebuild technology from first principles", as if that wasn't happening all the time, in the first place. We always strive to make things easier, cheaper, more robust, less dangerous…, with few exceptions. If you want to change something (e.g. about fossil fuels being a dominant source of energy), go learn and change that specific field. That effort is heroic enough! There's no "we don't think about other materials for this and that, because we've always done this and that". Research into fields that are far from commercial applicability is always happening, at large scale. There's thousands and thousands of engineers and scientists working to rebuild technology from its very foundations already!
* None of this can tackle the "you need an incredible concentration of resources to achieve innovation". The space technology example from the README is excellent: 

> Because the technology stack is so complex and expensive, you have to be a billionare to even attempt to verticly integrate any piece of it for innovation. 

No, that's not the problem. the rocket equation doesn't care about your motivation, or the depth of the technology stack. You'll need to have the resources to produce tons and tons of high-energy propellant, and incredibly robust engines. Going to the moon was a USSR/USA national level challenge in the 1960s, and without trying to bootstrap any of this without a humongous concentration of wealth/production means. Honestly, maybe you'd want to read Adam Smith and Karl Marx on production of goods, and how that requires huge-scale pooling of resources. And then maybe read a bit on modern theory on societies, trying to understand whether you'll be able to overcome the power structures this pooling brings (hint: few flat societies have launched a rocket or designed and produced a motorbike without depending on imports).
* The assumption that you could write down a document that allows people to understand from scratch, and on an implementable level, how to build modern devices, is admirable, bordering on cutely naive. Let me illustrate with the "how to build a CPU" [discussion](https://electronics.stackexchange.com/questions/528900/how-does-a-channel-know-to-drive-in-i2s-tdm-mode) from electronics.SE:
  * it requires knowledge from math / computer science to understand why a CPU is a CPU, why we choose to have CPUs, and how to approach the design of their command sets. That's >100 years of theory. Fills libraries. Easily a Bachelor's degree, even stripped down to a stupid "apply this, don't try to understand" level.
  * it requires knowledge from computer science / electrical engineering to understand how to approach actually desiging the logic. Same amount of theory as above.
  * it requires knowledge on electrical engineering how to power, clock and measure the in- and outputs. That's 200 years of knowledge. That's more than a master's degree in EE.
  * it requires 400 years of physics to understand why semiconductors work. Sure, you don't need all of a physics degree, because there's a lot of side knowledge that is only peripheral to the problem. But if you want to *understand* the technology, um, yeah, maybe a B.Sc. in physics would be good?
  * It requires extensive knowledge in chemistry to know how to prepare and process the materials needed for any feasible semiconductor. Good luck finding someone with that knowledge! (I'm ignoring the mining engineering / geoscience aspect here.) You'll need a theorist and a lab chemist and an expert on chemical processing.
  * It requires high-precision machinery to grow the crystals. Vacuum technology. High-temperature technology. Microscopy. High-Voltage generation. Lithography, most likely. Basically, you need 200 years of mechanical engineering and process design.

The knowledge necessary to build and understand the technology behind a 2€ pocket calculator would make the library of Alexandria look like a scrapbook.

Thank you for reading this; again, I'm not open for discussion.

**Comment by vitiral** [comment]
Hey Marcus, thank you for this perspective. I find a lot of what you are saying to be at the very least valuable caution -- this project is _very_ likely to fail, mostly because like any human endeavor it is likely to be dropped and forgotten about as all the other projects I have dropped and forgotten about.

I think the most important criticism here, which I need to fix before this bug is closed, is to clarify that CivBoot is a living concept. 500 people for 4 years is not a _requirement_ it is a _goal_. The real question is: how many people, for how long, with what resources? Reduce, reduce, reduce. Simplify, simplify, simplify. Having a distributed community of 5000 being able to build a Civboot from scratch with university-level resources would be a triumph. Can it be reduced? How much can it be reduced?

Rather than have a discussion (which you don't want) I just want to make a few clarifying points:
* Related to above, "first-principles" is too aggressive as a goal -- as you point out. Rather, perhaps the goal should be more along the lines of a _working understanding with references_. Clearly having a full understanding of how semiconductor materials work and why certain choices are made and how they can be altered, along with all the other fields of understanding, etc is far too aggressive. My hope is a CivBoot can be a starting point to such understanding, and can hold such references in it's databases.
* I do have _any problem_ with the complexity of current technology, nor do I intend to replicate it. The question is, how much can it be simplified and still be usable enough to replicate itself?
* This is a living project with a living definition. To achieve some things you have to reach beyond what is thought to be possible. As they say: it's not about the destination, it's about the journey.

Thanks again for taking a look and sharing your insight.

**Comment by ghost** [comment]
I have to admit that even me, who should understand your aim better than most, had a first reaction similar to @marcusmueller's. However, after a more careful read of the manifesto, I can see how his analysis is misunderstanding civboot's goal.

I believe that the root of the misunderstanding is that the preamble is too long and that our mind screams "naive! naive! naive!" before we reach an understanding of the project.

My opinion is that the manifesto would be better accepted if the following points were made very early:

1. We assume that technology in its current state has a complexity level adequate to the requirements we have. This is not a claim that technology in its current state could use some "fat trimming", complexity-wise.
2. Complexity trimming is achieved by drastically lowering requirements.
3. This project requires many highly dedicated people to ever hope to be successful.

Without the initial revulsion, the reader would be more inclined to read the whole manifesto and avoid misconceptions with regards to the project, which is seemingly what happened here.

That being said, I still believe that the project is naive because it is very unlikely to bring enough people to it before collapse hits the overdrive gear :) But I like the idea.

**Comment by ghost** [comment]
Something that I think is missing from the manifesto:

1. What do we want to "boot" to? New york with all modern comfort? Delhi? El Paso Texas? 19th century little towns?
2. Do we need Haber-Bosch or do we assume a more sustainable population level?
3. Does it need to be sustainable at level 1 or do we defer sustainability to level 3 (which makes reaching level 3 a hard requirement for our civilization)?
4. In "Requires no outside tooling besides commonly found materials (rocks, clay, wood, dirt, sand, ore, etc)", you don't mention any fossil fuel. What should be the target minimum EROI of available fuel for civboot to be successful? We've already spent easy energy. Booting from less energy is more of a challenge.

This goal you set will greatly affect the scope of the project. Also, if your requirement is a one of the big modern cities of the world, they are in complete contradiction with the "Should focus on the "single city" design" requirement. Modern comfort requires a global supply chain.

Considering that our current civilization is unsustainable with current technology levels, having a sustainability requirements addition to "New york with all modern comfort" would require us not to merely reboot current technology, but significantly improve upon it, possibly by inventing fusion.

**Comment by vitiral** [comment]
Thank you both for the feedback. I have entirely rewritten the README in the attempt to incorporate this feedback. I feel it is already significantly better. Further criticisms are welcome, either by re-opening this issue or creating a new one.

**Comment by vitiral** [comment]
@hsoft I did not address your points 3 or 4 regarding sustainability. To answer them, those are out of scope for the level 1 "educational" civboot. The energy would be provided by civilization or by some kind of gas/oil generator. Level 2 Civboot aims to rectify that as quickly as possible, however, and can provide all of it's energy through sustainable means.

**Comment by ghost** [comment]
The new wording is indeed much better. "Build a simple computer" is a much clearer statement than "bootstrap modern civilisation", and the added paragraphs about level 1, 2, tractors, etc. make a good job of illustrating where "build a computer" fits.

**Comment by amirouche** [comment]
I stumbled upon this repo one year after the OP. As far as I understand OP says it is impossible because it is too difficult. Nobody said it would be simple.

Regarding the usefulness of civboot project, it is clearly useful outside the "the civilization collapse". Getting together a warehouse to make a group of people build a sustainable village, city, eventually civilization on another planet is on the roadmap of many companies / states already.

**Comment by amirouche** [comment]
One common wisdom in programming making things simple is hard. So we can assume, one can rework current knowledge base and provide the tools in the warehouse both to dive into available or unavailable tool, to gain the knowledge that is missing.

**Comment by vitiral** [comment]
To touch on what @amirouche said, I also think there is value in having (even theoretically impossible) aspirational goals. For an example, just look at what SpaceX has done. Their goal is to build a million person colony on mars my like 2070 or something. Totally nuts, and yet having such a goal helps to reduce and simplify the problem space to the exact steps needed for achieving that goal. Maybe they will never achieve the goal, but achieving 4/10 steps _towards_ that goal has already altered the entire space industry.

**Comment by marcusmueller** [comment]
Amirouche, I've never heard of that "common wisdom" and it seems plain wishful thinking, not addressing a single point I've raised.

On October 2, 2021 8:37:25 PM GMT+02:00, amirouche ***@***.***> wrote:
>One common wisdom in programming making things simple is hard. So we can assume, one can rework current knowledge base and provide the tools in the warehouse both to dive into available or unavailable tool, to gain the knowledge that is missing.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/civboot/civboot/issues/1#issuecomment-932800641
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vitiral** [comment]
I agree, it didn't address a single point. It rather attempted to address
all of them. The point on simplicity has been said many times, perhaps you
would enjoy a read like this?

https://kottke.org/17/06/if-you-cant-explain-something-in-simple-terms-you-dont-understand-it

**Comment by marcusmueller** [comment]
The sentence

> if you can't explain something in simple terms you don't understand it

is pure nonsense; for example, you cannot explain  in simple terms why a transistor works; it requires an understanding of wide swaths of physics. Unless you're content with lies to children that don't actually explain anything.

**Comment by vitiral** [comment]
Hi Marcus, I find this to be an odd proposition. Of course you can explain in simple terms how a transistor works -- just search "how a transistor works" and you will find several simple explanations. In fact, all knowledge starts with simple explanations and builds more full understanding on top of it. If it doesn't, then it's very likely that the phenomenon is one that cannot be understood, or at least not communicated.

Are any of these explanations ever "complete"? Now we are getting philosophical. Philosophically no explanation is complete, since words and mathematics can only be approximations of reality. You cannot "completely" explain how sound is made any more than you can quench your thirst with the word "wet."

**Comment by marcusmueller** [comment]
I'm an electrical engineer. There is "sufficiently detailed" to explain something in other to make the way it works understandable. And there is "oversimplifying", where you make analogies that fall short of actually being accurate enough to explain the phenomenon to a degree that name the understanding useful for practical application.


All these "easy explanations" for transistors fall in the latter category.

**Comment by vitiral** [comment]
I'm a software engineer with BS's in physics and EE as well. Throughout my education and career I've always learned best if there was a simple explanation (sometimes overly simple) that could be used as a seed of understanding. I believe having a simple working model is extremely important for deepening understanding in an organic way. That's really all I'm trying to do here.

**Comment by marcusmueller** [comment]
That's awfully nice as series of youth books, but not very useful to reestablish a civilization

**Comment by vitiral** [comment]
I'm not so much trying to re-establish civilization as make a kernel which can be understood (if only surface level as you say), learned from and built on top of. I really hope civilization sticks around!
