### ISSUE TITLE
Thoughts on a formal specification language

### ISSUE THREAD

**Issue by orbitaldecay** [civboot/civboot#13]
## Introduction
I have been working on some fngi documentation on my fngi fork. I originally intended to write a single cxt document which outlined the current behavior of fngi and provided a simple introduction to programmers. After initiating the document, it occurred to me that writing a language specification and a separate pedagogical introduction may be a better path to take.

## High-level overview
Concerning the language specification, I had some basic ideas which I believe may be useful for the purposes of writing logically rigorous documents for the civboot project in general. I propose a document format with the following properties:

1. Documents written in this format should be text files readable by an untrained human (a human having no knowledge of the format). To an unknowing reader, it should just appear as typical text.
2. A tool should be written that allows for automated deduction of the consequences of statements in the document. The tool should support queries concerning said consequences.

The proposed tool will transpile the document format to datalog. Thus, two pieces of software would need to be written:

1. A so-called datalog "engine" (this is basically a datalog interpreter)
2. A procedure which transpiles the document format to datalog.

It probably makes sense to combine these into one program to skip a lot of intermediate steps.

## Brief introduction to datalog

Datalog is a so-called "logic programming language" which was original developed for the purposes of database development and query. It's implementation is remarkably simple for how powerful it is (I have implemented one in a weekend). An example of a datalog statement is:

(1) `human(orby).`

which reads colloquially in English as, "Orby is a human." or more technically, "The predicate 'human' is true of Orby." The period in datalog denotes the end of a statement. Another example of a datalog statement is:

(2) `mortal(X) :- human(X).`

which reads colloquially in English as, "X is mortal if X is human." Traditionally in datalog (and prolog), capital letters represent variables. ":-" represents a turnstile, which can be thought of colloquially as the word "if". We could also require multiple predicates to be true to satisfy `mortal(X)` such as `mortal(X) :- human(X), tall(X)` which says X is mortal if X is human and X is tall (the comma means *and* in this context). Such statements comprise a datalog program. Now we can issue queries to the program, such as:

`? mortal(X).`

which reads colloquially in English as, "Who is mortal?". The datalog engine should return:

`X = orby`

or, "Orby is mortal." which the engine deduces as a logical consequence of statements (1) and (2).

## Converting English to datalog

Here is one succinct and flexible way of converting English to datalog. The crux of the idea is simplify the datalog program down to a single predicate "p" which means: "This string of words is true".

The English words "*if*" and "*and*" are keywords in this proposed format. Sentences are separated by periods. A word beginning with @ is a variable. Consider the following excerpt:

Orby has a cat named Clementine. Clementine is evil. @X is a bad parent *if* @X has a cat named @Y *and* @Y is evil.

This would be converted to the datalog program:

```
p(orby, has, a, cat, named, clementine).
p(clementine, is, evil).
p(X, is, a, bad, parent) :- p(X, has, a cat, named, Y), p(Y, is, evil).
```

We could then query (in English): "@X is a bad parent?" to which we would receive the response: "Orby is a bad parent."

Aside: This could also be incorporated within cxt with a tag that implies that the statement is part of this language. When queries occur, all statements outside such a tag would be ignored.

Aside Aside: This is all actually way bigger than software documentation. This basic idea could be used to write about anything in a way that could be automatically reasoned about and queried.

**Comment by vitiral** [comment]
I think I understand the basics of datalog (as you have given them), but I fail to grasp how this could be generalized and scaled to a document of any kind written in english.

Your example `p(orby, has, a, cat, named, clementine)` would only trigger for _very specific_ queries. As we build logical structures of dependencies it would be more and more difficult to understand why a particular query wasn't working (i.e. synonyms such as "orby _owns_" instead of "orby _has_" would cause problems). It might be argued that this could be worked around using extremely terse language -- but then I worry we might harm the readability of the documentation with such language.

Funnily enough, this _seems_ to be trying to solve a similar problem as a search engine or even a large language model. Essentially you are attempting to craft a mechanism to encode knowledge into human speech -- something that has always failed (and is even today still failing IMO).

**Comment by orbitaldecay** [comment]
I think you raise an excellent point with the synonyms example. This idea relies on using very specific language to refer to a concept (identical in each case). On one hand, I am of the opinion that this promotes readability, but on the other hand increases the difficulty of writing a document (too easy to introduce "bugs" due to variations in phrasing). I don't know of a good way to solve this.

I debated going down the rabbit hole of introducing more structure (e.g. more keywords and more specific syntax), but I don't know how much that helps vs. complicates the implementation and learning curve.

As I am reflecting more, and considering your feedback, while I think this is an interesting idea, I also think it's probably too experimental to sink time into in this context. Let's shelve it for now. I might explore it on my own later, and I'll let you know if anything interesting comes out of it.

Thanks!

**Comment by vitiral** [comment]
Sounds good. I think there might be something really interesting here as well -- but it is more of a "research" subject rather than a "knowledge distillation."

I might label Civboot's fundamental _philosophical_ goal (as opposed to the _working_ goal of building a Civboot that can build itself) to be: distill the knowledge and processes of Civilization to be as simple as possible while remaining fully use-able.

I see fngi as a distillation of C (and a few other languages) by using the processes of forth and stack machines. This is how I hope most Civboot technology/documentation will be. There may be areas which need to be researched in order to fill in gaps -- thin film semiconductors are one such field -- but I hope those are relatively few. Instead, I'm hoping that simple ways to implement things can be found, such as Sam Zeloof's [microgram balance](https://hackaday.com/2018/11/19/of-roach-killer-and-rust-remover-sam-zeloofs-garage-made-chips/) "made from a panel meter movement".

In building fngi, I've found many such "shortcuts" that actually (in my opinion) simplify the language instead of making it feel more hacky.

**Comment by vitiral** [comment]
I'm going to go ahead and close this as not feasible. Feel free to re-open discussion.
