### ISSUE TITLE
Brainstorm stemming from your lead article

### ISSUE THREAD

**Issue by FabricioTeran** [civboot/civboot#6]
This is a draft, the ideas are messy and leave an open path to continue building them.

---

I believe that a solution to the messiness and complexity of the update (not the complexity of the system) are the 'standards'.

- Each standard would follow an RFC format (Request for comments)

For example:
- Create a standard for OOP object-oriented programming, a language-independent standard, explaining the ideas behind object-orientation, with examples of how implement it in middle-level languages ​​like C, but that the standard allows you to implement object-orientation in any middle-level language.
  - The standard would define its own namespace for keywords, but the implementor would be free to represent them as other words in their language syntax.
- A standard for defining language syntax, a standard explaining why haskell's syntax is the best for programming languages ​​and introducing new ideas for simpler syntax and that can describe complex algorithms with a couple of simple characters and symbols.
- A standard for drawing computer graphics: Developing a single specialized language for drawing computer graphics (again, language independent), taking the ideas
  of html, css and 2d and 3d graphic libraries such as OpenGL.
- A standard that defines what closures are
- A standard that defines what lexical scopes are
- A standard that defines concurrency and parallelism
- A standard that defines a language-independent intellisense program, including introducing AI ideas for language-independent code assistance and prediction
- ... A standard that defines what is a standard
- A standard for every single tool used in software enginering (collapsing all alternative tools in one single standard)

Each language has its own OOP implementation, lexical scope, concurrency/parallelism models, garbage collection, inheritance, polymorphism, typing, dynamic memory handling.

The standards would lead us to the creation of a single universal language: A language in which if you want you can choose to add OOP to your compiler, if you want to add Functional Orientation, define your own keywords, handle typing (whether it's static, dynamic or hybrid) and change it all at any time with a few clicks, no learning another 'language pack' with its own syntax, a unique orientation, no garbage collection and inefficient standard libraries, all because x technology is only available for language x.

In the universal language you can put together an OOP file, a functionally oriented file and a dynamically typed file and compile them into a single executable.

With these standards it would be possible to decouple all current software (unravel the spaghetti) and absolute freedom to choose only the necessary components to develop software and not depend on a whole 'tangled' software chain, some examples to explain my point above:
- Currently if you want to create a programming language, you can't take built pieces (which were already developed and thought long ago), you have to build it from scratch. You can find some information on how to build a lexer and parser, garbage collectors, but the information is generally incomplete, you have to search a lot of different places and you don't even have the latest advances in the field, the algorithms you find are the 'common practices', not the 'latest technology'. We don't want to build a TV from scratch (go to mine and extract the iron, create the transistors with your own hands or with a guide (the equivalent of a tutorial on how to build an AST software), etc) we just want the pieces already built and build our own custom TV, this is achieved with standards.
- Not actually

 BEGINNER 101

I think at this level of conversation it goes without saying that all existing programming languages ​​start out being developed in C (if you argue that such a language was developed in Java,
Java was developed in C and so with any language you can think of), therefore all computing concepts in all modern languages ​​are just 'syntactic sugar' built about the usual tools (if, for, pointers, arrays, etc. the real computing axioms), then we haven't invented anything new after C, we've just added more layers of abstraction that increasingly adapts better to the way our human brain works (each time tending to a human language and with more abstract ideas).

A program in go, java, c++, c, javascript, ruby, python, rust, etc. it ends up using the same processor assembly instructions as other programs just in a different order.

C language defines a cross-platform processor language,

**Comment by vitiral** [comment]
Note: I edited your comment to remove the large code block and fixed some formatting.

**Comment by vitiral** [comment]
I like your enthusiasm, but I think coming up with "standards" at this phase is a little too quick.

Let's see what's possible before we standardize.

> a standard explaining why haskell's syntax is the best for programming languages

I cannot tell if this is a joke or not...

A Civboot has a hard requirement that some small number of highschool-college students (i.e. 50 maybe as many as 500 for early civboots) must be able to _learn_ and _replicate_ it. Since many of the specialties in a Civboot must also learn computer programming, requiring everyone to learn Haskell (or a language like it) would be a significant portion of this cost.

I do think there are places for fully-functional languages; or if not pure-functional at least side-effect free (you can make any language side effect free by simply disabling all random numbers and IO!) The best place is for config languages, where you really are just wiggling bits with no input or output.

> I think at this level of conversation it goes without saying that all existing programming languages ​​start out being developed in C

My current thinking is that all Civboot languages (and the OS) will be developed in [fngi](https://github.com/civboot/fngi). Yes, the prototype is built in C but I want to try and make it self bootstrapping. Also I'd like to try and build a port in pure Z80 assembly, and eventually make a Civboot (probably stack-based) processor which can be a more "native" target for it. I'm inspired by [greenarrays](http://www.greenarraychips.com/) and the [J1](https://www.excamera.com/sphinx/fpga-j1.html)

C is a horribly complex language, although the [QBE](https://c9x.me/compile/) project and related [cproc](https://sr.ht/~mcf/cproc/) do give me some hope (they weight a combined total of ~20k lines of C -- most C compilers weigh well over 70k lines). By comparison fngi is 1.5k lines of C, then 1.5k lines of spor assembly. FORTHs can weigh far less than that, and many were written in pure assembly before C was really a thing. For low-level and understandable seeds there are better options than C.

**Comment by FabricioTeran** [comment]
> I like your enthusiasm, but I think coming up with "standards" at this phase is a little too quick.

Standards go through phases until they reach a stage of maturity (not final, updates go on forever), starting with drafts and growing with requests for comments or RFCs in which technical details are discussed and improvements are proposed.... That was exactly the process by which all the important internet protocols were developed: IP, TCP, UDP, DNS, HTTP, TLS, SSL, ETHERNET, IEEE802.11, etc.

It makes no sense to say that it is a very early stage to implement them, standardization is a long process that ranges from its draft to a mature version.

**Comment by FabricioTeran** [comment]
> I cannot tell if this is a joke or not...

It was not my intention to launch a joke, I would like to know why you perceived it as a joke

**Comment by vitiral** [comment]
> It makes no sense to say that it is a very early stage to implement them, standardization is a long process that ranges from its draft to a mature version.

Civboot is still in an experimental stage. Before you can make a standard you have to at least have an MVP.

There exist many other standards too chose from. Many of them are both well established and excellent. Few of them have the goals of Civboot.

> I would like to know why you perceived it as a joke

What you wrote was "a standard explaining why haskell's syntax is the best for programming languages"

Why is this funny? I guess if you don't get it, then it might be hard to explain, but I can try.

1. Standards are not rating systems. They don't describe why a particular programming language has the "best syntax."
2. Telling people what "the best" of anything is, especially in an area with so many tradeoffs as programming languages, is at best being extremely prescriptive. Civboot will pick a small subset of programming languages to use, but it will be because (1) at the end of the day _some_ language must be chosen and (2) a set of hopefully reasonable tradeoffs can be reasoned about.
3. Haskell is a specific (and very complicated) implementation of the ML family of syntaxes. Using "haskell" instead of "ML" is humorous.
4. Haskell is way out of the scope of the Civboot project. I highly doubt you could compile "hello world" in Haskell with less than 10 MiB of memory, much less 64KiB.

I don't think Civboot will begin defining standards at the moment. When we _do_ start to define standards, it will be with some experience and real progress under our belts.
