### ISSUE TITLE
silicon alternatives

### ISSUE THREAD

**Issue by jeanahelver** [civboot/civboot#7]
looking over it i don't think silicon could ever be feasible without allot of infrastructure. it also includes harder to make materials.
i know everyone here exited about integrated circuit micro chips. but unless we can do something in the vain of ink jet print something like a [plasticarm](https://hackaday.com/2021/07/23/arm-researchers-announce-the-plasticarm/) chip, i like to cover some logic gates tech made with simpler and more common resource.

### copper/iron age:
starting of is assuming the local resources are hardly anything, copper wire iron rods and some insulation material can create electromagnets, motors and for our computing needs relay's and switches. it can also output to punch cards or flip displays.
it would be extremely slow compared to silicon, but this is bootstrapping to drive and build CNC machines rolling of punch tape.
prerequisite tools would mostly contain of furnace and ore extraction. as a extreme long shot this might be a great option for mars.
the upside to this limited idea is that most of this can be done by hand with simple set of tools, making wire and coiling it around a iron core.

### photo resister logic:
this one i be honest i might be misunderstanding how the technology works. but insulating a [photoresistor](https://en.wikipedia.org/wiki/Photoresistor) together with a light emitter (lamp, led, neon) can create something that emulates a transistor to some extend.
requiring mostly metals in different forms like cadmium, indium and lead. the light source might also be a challenge as we cant use silicon leds.

### point-contact transistor:
silicon has made these obsolete nowadays as they be very expensive to produce compared to a chip. however the materials and manufacturing are not too insane. from what i understand after doping germanium it can mostly be achieved with mechanical processes.

#### design philosophy:
a somewhat intentional part on all of these is that they are not integrated at all on one piece (integrated). chip yields in small volumes would be a total waist of resources. having them as separate replaceable and reusable pieces could also open up more potential in adaptation/modification and improvements down the line and advancement.

apologies if this is more low spec then this project intended.

**Comment by vitiral** [comment]
> apologies if this is more low spec then this project intended.

Certainly not! In fact, this is _the hard problem_ that Civboot will have to solve. Many would call it the impossible problem, and that very likely may be true.

These are definitely some of the thoughts I have had as well. One important point is that the requirement is to be able to _build a civboot using a civboot_, or to put it another way: can you build a computer chip from scratch once you _already have a civboot_?

Therefore, I don't think copper or point-contact transistors are necessary -- and they are almost certainly the wrong approach (too manual, too inefficient, etc).

My current thinking is that [thin film transistors](https://github.com/civboot/civboot/blob/main/notes/hardware.md#thin-thin-film-transistors), using Tin or some other material, are probably the best approach here. They are low temperature, require fewer deadly chemicals and their backing material can be glass instead of 100% atomically pure silicone of perfect crystal structure.

**Comment by ghost** [comment]
I apologize if I'm being a doofus, but I can't see what the exact problem is with manufacturing silicone waffers.

Starting with your post #2: https://github.com/civboot/civboot/tree/main/podcasts/0002-semiconductor_fabrication.md , it was literally 2 seconds to land on a Wikipedia page of Mg2Si, and there I learned you can make it from elemental Mg and SiO2 using a bit of starter heat.

What's the big issue? Is it recycling magnesium? Because that's what I worry about when I see that.

And I also can't see what's the problem with waffer manufacture. Start with a crystal with known orientation. Orient it the way you want it oriented. Grow the crystal from it. Since the growing crystal has to conform to the original crystal seed, you will know what the orientation of your waffer is. Size the feedstock to the size of the waffer you want. Grind the excess off. Break a piece off to be the seed for the next batch. Use the remainder for chip manufacture.

What's the fuss?

If anything, @vitiral , you made me more optimistic about IC manufacture.

**Comment by vitiral** [comment]
> Mg2Si

Is Mg2Si a good semiconductor for digital circuits? Because it can't just be any-old semiconductor, it has to have specific properties to be usable for driving thousands (millions? billions?) of transistors with high speed, minimal energy loss, reasonable voltage, etc.

> And I also can't see what's the problem with wafer manufacture.

Well, first you need to create pure silicone. IIUC this is a bunch of exacting chemistry in ultra-cleanroom environments in a Nitrogen or similar atmosphere. Not impossible, but not exactly something you can do in your garage.

Then you have pure Si. Si melts at 2,570°F (1,410°C), which is one of the highest melting points of any material. To make a perfect crystal you need to melt it _without any impurities leaching into it_. In practice this means they melt it in a boule of SiO2 (melting point of 3,110°F/1,710°C). However, melting the silicone causes the boule to break, meaning you need to make a new boule for every batch of Silicone, so you better do it right. Then you need to saw the Si, aka quartz. You can pretty much only do this with diamond saws. Oh, and IIUC you have to saw it to be precisely along the crystal lattice (and I mean _precise_, I believe they are not off by even one atom). If any of this sounds easy, the 20-50 billion dollar price tag on these production facilities would beg to differ with you.

You can do floating zone production, but it will not produce at scale. And you still need to do diamond saws/etc.

Once you have the wafers, you then need to put ICs on them. This is definitely more possible, but far from trivial. At a minimum you will need toxic chemicals and high precision optics and machinery.

> Size the feedstock to the size of the waffer you want.

Ha. Wafers are grown by slowly pulling the seed crystal from the boule and rotating it. How slowly? What rotation? IIUC these are trade secrets, learned from countless billions of dollars of trial and error. Get off by the tiniest margin and you will have a smaller crystal or it won't be a perfect crystal.

**Comment by ghost** [comment]
I have to admit I misunderstood metallurgic silicon for magnesium silicon. Thus the mixup with Mg2Si. :)

As for the wafer manufacture: pretty impressive but remember that the modern processes are optimized for a different goal than civboot processes will be. :) I have to remember this every time I try to explore a technology I would want to use on a more personal scale.

How much silicon does a wafer factory need to make? 5 tons per year? 50? 500? But how much will a random civboot need to make? 5 grams per year? 500 grams? Because this optimization is different, new and interesting pathways can be open to you.

For example, after I figured out the difference between metallurgic silicon and Mg2Si, some things bobbled up to the surface. First, metallurgic silicon is used for producing iron alloys, not integrated circuits. They produce hundreds of tons of the stuff per year per facility - and that is where this problem of arc furnaces originates. Arc furnaces are for when you need to make 2 tons of the stuff per worker's shift. Is civboot going to operate at that scale? Second, metallurgic silicon - according to Wikipedia - needs to be purified to be useful for electronics.

And this is where I found an interesting pathway. You see, it turns out that Mg2Si can be treated with HCl to produce SiH4 (and MgCl2 which needs to be recycled into pure Mg by electrolysis after getting molten at ~700 degC - the same process produces Cl2 which gets recycled into HCl). And guess what? SiH4 decomposes at above 300 degC and can be used for vapor deposition. Hmm... I wonder what will be the purity of that deposed silicon... I'm pretty sure it's good enough for growing crystals.

And again - civboot might not need to use the most scalable method.

The diamond saws are interesting but I'm not overly impressed. Atoms are pretty small and I can't possibly imagine they are able to split a crystal right between two atoms such that the sheet of atoms on both sides of the cleavage (or even one) is unbroken. And that's even before taking into account silicon outgassing (not to mention oxydation) which has to happen at some rate.

For my purposes, in my own projects, I find it's best to **NOT** be in awe of "science" and technology but instead to give it the "signature look of superiority".

**Comment by vitiral** [comment]
The scale issue is exactly why I believe Civboot's future rests on thin
film lithography of low temperature semi-conductors. There are several Sn
based semiconductors that seem promising, and have already been
demonstrated to be able to build logic circuits: all deposited on glass,
which can be made at much lower temperatures.

High temperature ultra pure silicone requires a high scale production
facility. Thin film lithography could likely be produced in a small factory
or medium sized university, which is about right for Civboot IMO. You would
need clean rooms and precision engineering and optics, but you wouldn't
need 5,000 degree arc furnaces.

**Comment by vitiral** [comment]
The discussion seems to have died down, so closing this. Re-open if you have other thoughts!
