### ISSUE TITLE
Is Civboot a Book? 

### ISSUE THREAD

**Issue by komali2** [civboot/civboot#8]
I'd like to contribute to this project as it's something I often think about - if we built a small commune / community, how "off the grid" could we get? Topics like carpentry, husbandry, farming / gardening, ceramics etc are well covered, but where I always get stuck is computing and transistors, which a lot of "civboot"-aligned projects seem to discuss ( [this person](https://simplifier.neocities.org/) has some cool stuff going on glass). 

Anyway though, you mention a warehouse, though I'm unclear whether a civboot is the warehouse, or the instruction book on how to build the warehouse. I feel like the latter, as an instruction book can build many warehouses. On that note then, what needs to go into such a book? What's the table of contents? Based on "Must include all working knowledge..." its going to be at least as thick as an large encyclopedia, which makes sense. Basically, it's starting to sound like a large chunk of the book is going to need to be a schooling curriculum. I see that Open Source Ecology has a fantastic set of models of many tools, but no information on how to measure length, or map using geometry, or how to calculate load, gearing, etc. 

In short I sense a gap, that may readily be closed with libre curriculum. Portions of "The Civboot Book" could be asynchronously compiled by many experts, and the nature of a book could make for a good organizational tool in terms of determining what the project TODOs are, and as well as a framework for discussing what's relevant to the project's goals. 

For example, imagine the civboot project proposes the following (truncated) "Table of Contents":

# Volume 1: Baseline Educational Requirements

### Chapter 1: Elementary Math

1. Counting, especially beyond 10 and 17 (two common threshholds for numbering systems beyond which numbers become vaguely "many" or "infinity")
2. Adding and Subtracting
3. Multiplication 
4. Division, decimals, fractions
5. Exponents

Someone could pipe in and say "actually, I don't think exponents are necessary to the goals of the project." Someone else could say "Here's a libre elementary math textbook we can drop wholesale into the project." And so on for other Chapters / Sections / Volumes. 

Other advantages include:

1. General passion for libre / free / open educational materials out there in the world. See: Indian Youtube, [Khan Academy](https://www.khanacademy.org/), FreeCodeCamp, millions of others. Have a chat with anybody in education to see just how far reaching and important libre curriculum and course materials are, *especially* in the developing world. This could increase number of contributors and general attention paid to the project.
2. Immediately useful: The civboot project, as a repository / generator of libre educational materials, could function as an index/library of immediate use to people all over the world. This could increase possibility of funding, general attention to project, number of contributors, etc. 

Thanks for leaving space here for me to braindump. I'm very interested in feedback for any willing to provide it.

**Comment by vitiral** [comment]
> I'd like to contribute to this project as it's something I often think about - if we built a small commune / community, how "off the grid" could we get? Topics like carpentry, husbandry, farming / gardening, ceramics etc are well covered, but where I always get stuck is computing and transistors, which a lot of "civboot"-aligned projects seem to discuss ( [this person](https://simplifier.neocities.org/) has some cool stuff going on glass).

Awesome, welcome! I agree, computing and precision engineering are definitely the _hard_ problems, which is why I'm targeting them.

> Anyway though, you mention a warehouse, though I'm unclear whether a civboot is the warehouse, or the instruction book on how to build the warehouse. I feel like the latter, as an instruction book can build many warehouses. 

Both.

The thing to understand is that you can't build a computer (or precision engineering) unless you already have both. It's just like the chicken and the egg, where we didn't get either without the iterative cycle of breeding (after selecting the initial birds from the wild of course).

A Civboot therefore has to be a warehouse which can build a computer, precision engineering tools etc... whatever is needed to build _another Civboot_. Without this "simplest base" it is impossible to have anything like a "full grasp" of the complexity of our technological underpinnings.

The core question is: how many warehouses do you need to be able to build another Civboot? Currently the answer is probably approximately: a warehouse the size of China. At best: a warehouse the size of Silicon Valley.

Regarding the rest of your "braindump" as you put it, I think you are on the right track :smile: My intent was to incorporate libre knowledge into the Civboot as I went along.

**Comment by komali2** [comment]
It sounds like the warehouse would be unnecessary, if we were able to provide an instruction book on how to get from hammering bronze to making iron anvils to making assembly lines to making vacuum tubes to, finally, making transistors, BUT, we instead want to allow people to skip the "from scratch" part of that, cut out the vacuum tube section of the "Civilization Instruction Manual" entirely, and replace it with "How to Use The Fabrication Machine inside the Civboot Warehouse" ? That is to say a civboot warehouse shouldn't need now-surpassed technologies like water computers or whatever because they'll be able to fabricate silicon chips (or something far better than vacuum tubes but can't be made without the precursor materials being provided by a global supply chain that may or may not continue to exist) ?

**Comment by vitiral** [comment]
Exactly. Starting at the bronze age is not feasible. You are essentially talking about a concentrated version of (at least) the last hundred years. And no amount of books are going to "rediscover" the materials science of those hundred years without extreme cost. It took thousands upon thousands of engineers to discover "simple" solutions to these things, but many of those solutions require previous iterations of the solutions (hence chicken and egg).

Silicon is probably too difficult (requiring billion+ dollar fabs, ultra high temperatures and ultra poisonous chemicals). My personal hope right now rests in thin film semiconductors, possibly Tin or a similar material. They can be manufactured at low temperatures on a glass (not pure silicon) substrate, and should be (in fact are currently) possible at a "university" scale.

**Comment by vitiral** [comment]
By "hundred years" I mean that getting to the industrial revolution is easy -- that really _can_ be done in just a few books with a few months of effort. You can forge the pieces needed for a lathe from scrape iron in molds made from sand and then wallah, you can build practically every tool you need.

But you can't (easily) use just a crude lathe to construct the precision tooling needed to design and manufacture computer chips... or even the optics and precision machinery needed to _begin_ constructing modern computer chips. I very much doubt you could even build a proper vacuum tube in a human lifetime with such a strategy.

**Comment by komali2** [comment]
Good food for thought, and I really enjoyed looking into thin film conductors, thanks for that. Sidenote on vaccuum tubes, you may be right, though that "simplifier" person [did some interesting stuff with bulbs](https://simplifier.neocities.org/portable.html), though I think they was working with some pretty big industrial equipment based on the pics. Haven't read through their entire photo blog yet to see the whole process. 

At th point, I'm mostly interested in seeing what kind organizational (as in, the act of organizing things) effort might help. The project has clear enough goals, constraints, and timeline ("progress" section on README), but  what about deeper task breakdowns, TODOs, "areas needing help," etc? If this sort of thing doesn't exist and project members believe would be helpful, is there interest in me working cooperatively in laying out that sort of thing? Not to get all project managementy, but, do we want someone to start writing out, essentially, "tickets?" 

I ask because I want to help, but I'm not really sure where the project is at, what the next steps / goals are, and who's working on what sort of things. Perhaps once I get through the podcast I'll have a better idea!

**Comment by vitiral** [comment]
> I ask because I want to help, but I'm not really sure where the project is at, what the next steps / goals are, and who's working on what sort of things. Perhaps once I get through the podcast I'll have a better idea!

I am currently the only active developer (that I know of), although there are a few people who are interested in the project. So if you want to work on something which is at the ground-state, then this is a great project!

The current state of the project is more developed on the software side: I'm trying to create http://github.com/civboot/fngi. I believe I can create a full programming language, compiler and operating system that only requires ~128KiB of RAM. Add on maybe a few MiB of ram, and you can run software necessary for an efficient Civboot (primarily: text editor, programmatic CAD tooling for machining and computer chips, automation software for robots, educational programs, etc). Just the software side is clearly impossible for one person, but I believe I can start the foundation.

A finished software OS will give the hardware side of Civboot something to target. Maybe a multi-core (although it will be a different architecture... I have a few ideas on that) 100MHz processor with a few MiB of RAM.

Everything used by the Civboot should be built by the Civboot.... eventually. It should also allow for off-the-shelf components with similar specs (i.e. constraints) to implement the functionality. IMO whether the hardware is built externally or by the Civboot, it should all run fngi (or whatever software we center on).

I'd say the high-level points are the following, which may be accomplished in any order:

1. Develop the core software kernel (fngi) and attract an OSS development community to help build out the necessary software for Civboot.
2. Start self-cycles on machining side. For example, build a machining shop which has the tools necessary to build a _new_ machining shop. It would be great if we could build cheap machining shops/etc for new members. Keep building this up in larger and larger complexity until we have precision machining (_at least_ 30 years out IMO, even if we have extensive resources)
3. Cooperate with universities to try and create a process for building semiconductors at low temperature/low cost. Simultaneously develop and mass-manufacturer (with conventional facilities) an ultra-simple computer chip and hardware components to run CivbootOS.
4. Solve other hardware problems. Display (LCD?), storage (floppy drive?), hardware peripherals, communication, etc.

However, listing these out is pure imagination without others interested in the project. For me personally, I'm just having a fun time building the software side and experimenting with hardware. I also have three young children, a small hobby farm and a full time job, so my time is fairly limited.

I definitely appreciate any new perspective you would like to offer. I personally see this as the ultimate life project, the most clear way to personally leave a real positive impact on the future. I hope others feel that way too, because otherwise it's not only practically impossible but actually impossible.

**Comment by komali2** [comment]
You're certainly not alone in looking for ways to preserve for the future a way to continue the comforts, safety, and bounty offered to us by modern technology! In a way the cause is aligned perfectly with various niche communities like datahoarders / archivists, right to repair advocates, copyleft folks, and all sorts of digital activists. If you haven't ready Walkaway by Cory Doctorow, I highly recommend it, it's the first thing I thought of when I found this project. 

As for creating a process for building semiconductors at low temperature and cost, the first step may be to investigate the research already done on the subject? I have an interest in this and have been meaning to look into it, and am happy to share what I learn. That could then be compiled with this project and would improve the ease of pitching to a university: "here's what we have so far, what do you think? Any improvements? Want to put some students on this for a project they can turn in for credit for xyz class?"

**Comment by vitiral** [comment]
I agree, it's a different take on a few different approaches. What it
offers for me is a single clear and achievable, albeit very difficult,
goal. I like having a goal, it clarifies what is needed and strips
unnecessary dependencies.

You caught me at a time when I was actively searching for a sci-fi
audiobook to listen to at the gym and during farmwork. Downloading it now
from my local library (hoopla app, can't recommend it enough).

Compiling current research on feasible approaches for electronics
fabrication is something that is sorely needed, and i would very much
appreciate any help you can offer. Even just links to papers with snippets
relevant to Civboot would be helpful, but obviously digging into specific
approaches would be equally valuable.

The approach of trying to involve universities is the right one I think.
Fundamentally this is an education driven project that I think would be a
significant boon for technical universities, and something they can also be
instrumental in helping to make.

**Comment by yarivaltean** [comment]
If y'all need university connections I have a few, would be happy to try and build those bridges and write out the letters to them once the work is compiled. I don't have much in the way of spare time that can be given to a project like this, and most of what y'all are talking about is beyond my realm of expertise, but I'm happy to help where I can - this is a really important project.

**Comment by vitiral** [comment]
@komali2 I'm about halfway through Walkaway -- it's an excellent book so far, thanks for the suggestion! The bots and printers definitely have some similarities to a Civboot, and if they existed I would definitely call a small collection of them a Civboot. They are a bit more automated than I would want a Civboot to be (IMO high automation = less understandable), but as a possible place to reach _beyond_ a Civboot I think the writer's depiction of them could be an inspiration for someone with a futurist perspective; which is not my own perspective, but I understand the allure.

@yarivaltean I definitely appreciate any way to spread the vision of a Civboot. It's not going to happen with just my effort, I am far too small and stupid to solve even 5% of the problems by myself. I don't think I'll be able to "compile the work" necessary for at least a few more years, so if you or anyone else (speaking to readers of this issue, if there are any) were interested in the work it would be _very_ appreciated. IMO the ideal would be a packaged-up grant application, just waiting for a researcher to pick it up.

**Comment by komali2** [comment]
I found another person doing home lab transistors! http://sam.zeloof.xyz/category/semiconductor/

**Comment by vitiral** [comment]
Yup! He's super impressive. However, he buys sawed wafers from the fab --
and that is by far the hardest part. There are similar labs to his at many
universities (I've even personally made a transistor in one!)

**Comment by vitiral** [comment]
Going to go ahead and close this now. "Book-like" documentation is definitely something I want, and I'll open an issue when it is closer to a reality.
